export const ASYNC_GET_SUBREDDIT = 'ASYNC_GET_SUBREDDIT';
export const GET_SUBREDDIT = 'GET_SUBREDDIT';
export const REQUEST_SUBREDDIT = 'REQUEST_SUBREDDIT';
export const FAILED_REQUEST = 'FAILED_REQUEST';